// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/admin.proto

package adminv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutboxStatus int32

const (
	OutboxStatus_OUTBOX_STATUS_UNSPECIFIED OutboxStatus = 0
	OutboxStatus_OUTBOX_STATUS_PENDING     OutboxStatus = 1
	OutboxStatus_OUTBOX_STATUS_FAILED      OutboxStatus = 2
	OutboxStatus_OUTBOX_STATUS_PUBLISHED   OutboxStatus = 3
)

// Enum value maps for OutboxStatus.
var (
	OutboxStatus_name = map[int32]string{
		0: "OUTBOX_STATUS_UNSPECIFIED",
		1: "OUTBOX_STATUS_PENDING",
		2: "OUTBOX_STATUS_FAILED",
		3: "OUTBOX_STATUS_PUBLISHED",
	}
	OutboxStatus_value = map[string]int32{
		"OUTBOX_STATUS_UNSPECIFIED": 0,
		"OUTBOX_STATUS_PENDING":     1,
		"OUTBOX_STATUS_FAILED":      2,
		"OUTBOX_STATUS_PUBLISHED":   3,
	}
)

func (x OutboxStatus) Enum() *OutboxStatus {
	p := new(OutboxStatus)
	*p = x
	return p
}

func (x OutboxStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OutboxStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_admin_proto_enumTypes[0].Descriptor()
}

func (OutboxStatus) Type() protoreflect.EnumType {
	return &file_proto_admin_proto_enumTypes[0]
}

func (x OutboxStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OutboxStatus.Descriptor instead.
func (OutboxStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

type ListOutboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        OutboxStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=ledgerflow.admin.v1.OutboxStatus" json:"status,omitempty"`
	Limit         uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutboxRequest) Reset() {
	*x = ListOutboxRequest{}
	mi := &file_proto_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutboxRequest) ProtoMessage() {}

func (x *ListOutboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutboxRequest.ProtoReflect.Descriptor instead.
func (*ListOutboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{0}
}

func (x *ListOutboxRequest) GetStatus() OutboxStatus {
	if x != nil {
		return x.Status
	}
	return OutboxStatus_OUTBOX_STATUS_UNSPECIFIED
}

func (x *ListOutboxRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type OutboxItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Attempts      int32                  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	NextAttemptAt string                 `protobuf:"bytes,5,opt,name=next_attempt_at,json=nextAttemptAt,proto3" json:"next_attempt_at,omitempty"`
	LockedBy      string                 `protobuf:"bytes,6,opt,name=locked_by,json=lockedBy,proto3" json:"locked_by,omitempty"`
	LockedAt      string                 `protobuf:"bytes,7,opt,name=locked_at,json=lockedAt,proto3" json:"locked_at,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,8,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	LastError     string                 `protobuf:"bytes,9,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboxItem) Reset() {
	*x = OutboxItem{}
	mi := &file_proto_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboxItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxItem) ProtoMessage() {}

func (x *OutboxItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxItem.ProtoReflect.Descriptor instead.
func (*OutboxItem) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{1}
}

func (x *OutboxItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutboxItem) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OutboxItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *OutboxItem) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *OutboxItem) GetNextAttemptAt() string {
	if x != nil {
		return x.NextAttemptAt
	}
	return ""
}

func (x *OutboxItem) GetLockedBy() string {
	if x != nil {
		return x.LockedBy
	}
	return ""
}

func (x *OutboxItem) GetLockedAt() string {
	if x != nil {
		return x.LockedAt
	}
	return ""
}

func (x *OutboxItem) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *OutboxItem) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ListOutboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*OutboxItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOutboxResponse) Reset() {
	*x = ListOutboxResponse{}
	mi := &file_proto_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOutboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOutboxResponse) ProtoMessage() {}

func (x *ListOutboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOutboxResponse.ProtoReflect.Descriptor instead.
func (*ListOutboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{2}
}

func (x *ListOutboxResponse) GetItems() []*OutboxItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type GetOutboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutboxRequest) Reset() {
	*x = GetOutboxRequest{}
	mi := &file_proto_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutboxRequest) ProtoMessage() {}

func (x *GetOutboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutboxRequest.ProtoReflect.Descriptor instead.
func (*GetOutboxRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{3}
}

func (x *GetOutboxRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOutboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *OutboxItem            `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOutboxResponse) Reset() {
	*x = GetOutboxResponse{}
	mi := &file_proto_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOutboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOutboxResponse) ProtoMessage() {}

func (x *GetOutboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOutboxResponse.ProtoReflect.Descriptor instead.
func (*GetOutboxResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetOutboxResponse) GetItem() *OutboxItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type ListDlqRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDlqRequest) Reset() {
	*x = ListDlqRequest{}
	mi := &file_proto_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDlqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDlqRequest) ProtoMessage() {}

func (x *ListDlqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDlqRequest.ProtoReflect.Descriptor instead.
func (*ListDlqRequest) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListDlqRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DlqItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	AggregateId   string                 `protobuf:"bytes,3,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	DlqAt         string                 `protobuf:"bytes,5,opt,name=dlq_at,json=dlqAt,proto3" json:"dlq_at,omitempty"`
	Attempts      int32                  `protobuf:"varint,6,opt,name=attempts,proto3" json:"attempts,omitempty"`
	LastError     string                 `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DlqItem) Reset() {
	*x = DlqItem{}
	mi := &file_proto_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DlqItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DlqItem) ProtoMessage() {}

func (x *DlqItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DlqItem.ProtoReflect.Descriptor instead.
func (*DlqItem) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{6}
}

func (x *DlqItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DlqItem) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *DlqItem) GetAggregateId() string {
	if x != nil {
		return x.AggregateId
	}
	return ""
}

func (x *DlqItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *DlqItem) GetDlqAt() string {
	if x != nil {
		return x.DlqAt
	}
	return ""
}

func (x *DlqItem) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *DlqItem) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ListDlqResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DlqItem             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDlqResponse) Reset() {
	*x = ListDlqResponse{}
	mi := &file_proto_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDlqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDlqResponse) ProtoMessage() {}

func (x *ListDlqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDlqResponse.ProtoReflect.Descriptor instead.
func (*ListDlqResponse) Descriptor() ([]byte, []int) {
	return file_proto_admin_proto_rawDescGZIP(), []int{7}
}

func (x *ListDlqResponse) GetItems() []*DlqItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_proto_admin_proto protoreflect.FileDescriptor

const file_proto_admin_proto_rawDesc = "" +
	"\n" +
	"\x11proto/admin.proto\x12\x13ledgerflow.admin.v1\"d\n" +
	"\x11ListOutboxRequest\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.ledgerflow.admin.v1.OutboxStatusR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\"\x9a\x02\n" +
	"\n" +
	"OutboxItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts\x12&\n" +
	"\x0fnext_attempt_at\x18\x05 \x01(\tR\rnextAttemptAt\x12\x1b\n" +
	"\tlocked_by\x18\x06 \x01(\tR\blockedBy\x12\x1b\n" +
	"\tlocked_at\x18\a \x01(\tR\blockedAt\x12!\n" +
	"\fpublished_at\x18\b \x01(\tR\vpublishedAt\x12\x1d\n" +
	"\n" +
	"last_error\x18\t \x01(\tR\tlastError\"K\n" +
	"\x12ListOutboxResponse\x125\n" +
	"\x05items\x18\x01 \x03(\v2\x1f.ledgerflow.admin.v1.OutboxItemR\x05items\"\"\n" +
	"\x10GetOutboxRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x11GetOutboxResponse\x123\n" +
	"\x04item\x18\x01 \x01(\v2\x1f.ledgerflow.admin.v1.OutboxItemR\x04item\"&\n" +
	"\x0eListDlqRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\"\xcc\x01\n" +
	"\aDlqItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12!\n" +
	"\faggregate_id\x18\x03 \x01(\tR\vaggregateId\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\x12\x15\n" +
	"\x06dlq_at\x18\x05 \x01(\tR\x05dlqAt\x12\x1a\n" +
	"\battempts\x18\x06 \x01(\x05R\battempts\x12\x1d\n" +
	"\n" +
	"last_error\x18\a \x01(\tR\tlastError\"E\n" +
	"\x0fListDlqResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.ledgerflow.admin.v1.DlqItemR\x05items*\x7f\n" +
	"\fOutboxStatus\x12\x1d\n" +
	"\x19OUTBOX_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15OUTBOX_STATUS_PENDING\x10\x01\x12\x18\n" +
	"\x14OUTBOX_STATUS_FAILED\x10\x02\x12\x1b\n" +
	"\x17OUTBOX_STATUS_PUBLISHED\x10\x032\x9f\x02\n" +
	"\fAdminService\x12]\n" +
	"\n" +
	"ListOutbox\x12&.ledgerflow.admin.v1.ListOutboxRequest\x1a'.ledgerflow.admin.v1.ListOutboxResponse\x12Z\n" +
	"\tGetOutbox\x12%.ledgerflow.admin.v1.GetOutboxRequest\x1a&.ledgerflow.admin.v1.GetOutboxResponse\x12T\n" +
	"\aListDlq\x12#.ledgerflow.admin.v1.ListDlqRequest\x1a$.ledgerflow.admin.v1.ListDlqResponseB\x1fZ\x1dledger-go/gen/adminv1;adminv1b\x06proto3"

var (
	file_proto_admin_proto_rawDescOnce sync.Once
	file_proto_admin_proto_rawDescData []byte
)

func file_proto_admin_proto_rawDescGZIP() []byte {
	file_proto_admin_proto_rawDescOnce.Do(func() {
		file_proto_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)))
	})
	return file_proto_admin_proto_rawDescData
}

var file_proto_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_admin_proto_goTypes = []any{
	(OutboxStatus)(0),          // 0: ledgerflow.admin.v1.OutboxStatus
	(*ListOutboxRequest)(nil),  // 1: ledgerflow.admin.v1.ListOutboxRequest
	(*OutboxItem)(nil),         // 2: ledgerflow.admin.v1.OutboxItem
	(*ListOutboxResponse)(nil), // 3: ledgerflow.admin.v1.ListOutboxResponse
	(*GetOutboxRequest)(nil),   // 4: ledgerflow.admin.v1.GetOutboxRequest
	(*GetOutboxResponse)(nil),  // 5: ledgerflow.admin.v1.GetOutboxResponse
	(*ListDlqRequest)(nil),     // 6: ledgerflow.admin.v1.ListDlqRequest
	(*DlqItem)(nil),            // 7: ledgerflow.admin.v1.DlqItem
	(*ListDlqResponse)(nil),    // 8: ledgerflow.admin.v1.ListDlqResponse
}
var file_proto_admin_proto_depIdxs = []int32{
	0, // 0: ledgerflow.admin.v1.ListOutboxRequest.status:type_name -> ledgerflow.admin.v1.OutboxStatus
	2, // 1: ledgerflow.admin.v1.ListOutboxResponse.items:type_name -> ledgerflow.admin.v1.OutboxItem
	2, // 2: ledgerflow.admin.v1.GetOutboxResponse.item:type_name -> ledgerflow.admin.v1.OutboxItem
	7, // 3: ledgerflow.admin.v1.ListDlqResponse.items:type_name -> ledgerflow.admin.v1.DlqItem
	1, // 4: ledgerflow.admin.v1.AdminService.ListOutbox:input_type -> ledgerflow.admin.v1.ListOutboxRequest
	4, // 5: ledgerflow.admin.v1.AdminService.GetOutbox:input_type -> ledgerflow.admin.v1.GetOutboxRequest
	6, // 6: ledgerflow.admin.v1.AdminService.ListDlq:input_type -> ledgerflow.admin.v1.ListDlqRequest
	3, // 7: ledgerflow.admin.v1.AdminService.ListOutbox:output_type -> ledgerflow.admin.v1.ListOutboxResponse
	5, // 8: ledgerflow.admin.v1.AdminService.GetOutbox:output_type -> ledgerflow.admin.v1.GetOutboxResponse
	8, // 9: ledgerflow.admin.v1.AdminService.ListDlq:output_type -> ledgerflow.admin.v1.ListDlqResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_admin_proto_init() }
func file_proto_admin_proto_init() {
	if File_proto_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_admin_proto_rawDesc), len(file_proto_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_admin_proto_goTypes,
		DependencyIndexes: file_proto_admin_proto_depIdxs,
		EnumInfos:         file_proto_admin_proto_enumTypes,
		MessageInfos:      file_proto_admin_proto_msgTypes,
	}.Build()
	File_proto_admin_proto = out.File
	file_proto_admin_proto_goTypes = nil
	file_proto_admin_proto_depIdxs = nil
}
