# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: admin.proto for package 'ledgerflow.admin.v1'

require 'grpc'
require_relative 'admin_pb'

module Ledgerflow
  module Admin
    module V1
      module AdminService
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'ledgerflow.admin.v1.AdminService'

          rpc :ListOutbox, ::Ledgerflow::Admin::V1::ListOutboxRequest, ::Ledgerflow::Admin::V1::ListOutboxResponse
          rpc :GetOutbox, ::Ledgerflow::Admin::V1::GetOutboxRequest, ::Ledgerflow::Admin::V1::GetOutboxResponse
          rpc :ListDlq, ::Ledgerflow::Admin::V1::ListDlqRequest, ::Ledgerflow::Admin::V1::ListDlqResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
