# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: admin.proto

require 'google/protobuf'


descriptor_data = "\n\x0b\x61\x64min.proto\x12\x13ledgerflow.admin.v1\"U\n\x11ListOutboxRequest\x12\x31\n\x06status\x18\x01 \x01(\x0e\x32!.ledgerflow.admin.v1.OutboxStatus\x12\r\n\x05limit\x18\x02 \x01(\r\"\xbb\x01\n\nOutboxItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\t\x12\x10\n\x08\x61ttempts\x18\x04 \x01(\x05\x12\x17\n\x0fnext_attempt_at\x18\x05 \x01(\t\x12\x11\n\tlocked_by\x18\x06 \x01(\t\x12\x11\n\tlocked_at\x18\x07 \x01(\t\x12\x14\n\x0cpublished_at\x18\x08 \x01(\t\x12\x12\n\nlast_error\x18\t \x01(\t\"D\n\x12ListOutboxResponse\x12.\n\x05items\x18\x01 \x03(\x0b\x32\x1f.ledgerflow.admin.v1.OutboxItem\"\x1e\n\x10GetOutboxRequest\x12\n\n\x02id\x18\x01 \x01(\t\"B\n\x11GetOutboxResponse\x12-\n\x04item\x18\x01 \x01(\x0b\x32\x1f.ledgerflow.admin.v1.OutboxItem\"\x1f\n\x0eListDlqRequest\x12\r\n\x05limit\x18\x01 \x01(\r\"\x89\x01\n\x07\x44lqItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x14\n\x0c\x61ggregate_id\x18\x03 \x01(\t\x12\x12\n\ncreated_at\x18\x04 \x01(\t\x12\x0e\n\x06\x64lq_at\x18\x05 \x01(\t\x12\x10\n\x08\x61ttempts\x18\x06 \x01(\x05\x12\x12\n\nlast_error\x18\x07 \x01(\t\">\n\x0fListDlqResponse\x12+\n\x05items\x18\x01 \x03(\x0b\x32\x1c.ledgerflow.admin.v1.DlqItem*\x7f\n\x0cOutboxStatus\x12\x1d\n\x19OUTBOX_STATUS_UNSPECIFIED\x10\x00\x12\x19\n\x15OUTBOX_STATUS_PENDING\x10\x01\x12\x18\n\x14OUTBOX_STATUS_FAILED\x10\x02\x12\x1b\n\x17OUTBOX_STATUS_PUBLISHED\x10\x03\x32\x9f\x02\n\x0c\x41\x64minService\x12]\n\nListOutbox\x12&.ledgerflow.admin.v1.ListOutboxRequest\x1a\'.ledgerflow.admin.v1.ListOutboxResponse\x12Z\n\tGetOutbox\x12%.ledgerflow.admin.v1.GetOutboxRequest\x1a&.ledgerflow.admin.v1.GetOutboxResponse\x12T\n\x07ListDlq\x12#.ledgerflow.admin.v1.ListDlqRequest\x1a$.ledgerflow.admin.v1.ListDlqResponseB\x1fZ\x1dledger-go/gen/adminv1;adminv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Ledgerflow
  module Admin
    module V1
      ListOutboxRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ledgerflow.admin.v1.ListOutboxRequest").msgclass
      OutboxItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ledgerflow.admin.v1.OutboxItem").msgclass
      ListOutboxResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ledgerflow.admin.v1.ListOutboxResponse").msgclass
      GetOutboxRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ledgerflow.admin.v1.GetOutboxRequest").msgclass
      GetOutboxResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ledgerflow.admin.v1.GetOutboxResponse").msgclass
      ListDlqRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ledgerflow.admin.v1.ListDlqRequest").msgclass
      DlqItem = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ledgerflow.admin.v1.DlqItem").msgclass
      ListDlqResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ledgerflow.admin.v1.ListDlqResponse").msgclass
      OutboxStatus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ledgerflow.admin.v1.OutboxStatus").enummodule
    end
  end
end
